# baseurl: "/kyreefisher"
url: https://cowthat.github.io


collections:
  projects:
    output: true
    permalink: /projects/:name
    order:
      - vcuarts-gift-guide.html
      - guide-to-gdes.html


defaults:
  - scope:
      path: ""
      type: "project"
    values:
      layout: "project"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
