url: https://kyreefisher.com


collections:
  projects:
    output: true
    permalink: /projects/:name
    # order:
    #   - vcuarts-gift-guide.html
    #   - guide-to-gdes.html
  projects-unfinished:
    output: true
    permalink: /gallery/:name


defaults:
  - scope:
      path: "_projects/"
      type: "project"
    values:
      layout: "project"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  # - scope:
  #     path: ""
  #   values:
  #     layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

